### ISSUE TITLE
Не считает Aggregate rating

### ISSUE THREAD

**Issue by loveorigami** [Chiliec/yii2-vote#1]
Сделал все по инструкции, добавил в таблицу поля 
- rating    smallint(6)
- aggregate_rating  float(3,2)

Выполнил голосование под 3 уч. записями
Поле rating изменило свое значение на 3, а aggregate_rating осталось пустым.
![01](https://cloud.githubusercontent.com/assets/98164/5892005/67fd3c02-a4c2-11e4-8d07-b359b3096fac.jpg)
![02](https://cloud.githubusercontent.com/assets/98164/5892006/67fed062-a4c2-11e4-859b-5a68b89f6b0d.jpg)

**Comment by chiliec** [comment]
Дьявол в деталях... По инструкции написано `unsigned` для поля `aggregate_rating` :smiling_imp:

**Comment by loveorigami** [comment]
Поменял атрибут поля на unsigned. Очистил весь кеш и таблицу.
Теперь считает, но кажется - неправильно.
Для разных вариантов - один и тот же рейтинг.
![2015-01-25_21-52-01](https://cloud.githubusercontent.com/assets/98164/5892791/99da9a34-a4dc-11e4-9e89-86117f2f020d.jpg)

**Comment by chiliec** [comment]
Это уже [кеширование](https://github.com/Chiliec/yii2-vote/blob/master/models/Rating.php#L111) работает, надо будет уменьшить это время.

**Comment by chiliec** [comment]
Исправил, после обновления рейтинг должен отображаться правильно.
