### ISSUE TITLE
если вместо id например news_id как запускать?

### ISSUE THREAD

**Issue by fourclub** [Chiliec/yii2-vote#13]
если вместо id например news_id как запускать?

если прописать вместо id ( 'target_id' => $model->news_id,) то будет ошибка такая:
Getting unknown property: app\models\News::id

**Comment by chiliec** [comment]
Пофиксил https://github.com/Chiliec/yii2-vote/commit/946fcf466130915c8aa28504d013f2adf91604b8, обновитесь пожалуйста.
