### ISSUE TITLE
обновился теперь с news_id показывает все но

### ISSUE THREAD

**Issue by fourclub** [Chiliec/yii2-vote#14]
обновился теперь с news_id показывает все но по нажатию на голос за или против пишется всегда: Bad Request

**Comment by chiliec** [comment]
А если behavior к модели не подключать, то нормально проходят? 
Можно мне как-то Ваше кодо-окружение у себя посмотреть?

**Comment by fourclub** [comment]
у меня локально сайт, в инете нету. Сделал все по инструкции, установил, в конфиг модуль, в модель behavior в вьюшку <?php echo \chiliec\vote\Display::widget([ ..... 
в бд поля и таблицу...

**Comment by chiliec** [comment]
Ну всё равно надо как-то понять в чем причина, потому что у меня нормально работает.
В модель behavior добавлять в принципе необязательно. Так вот, если её не добавлять, то запросы проходят?

**Comment by fourclub** [comment]
убрал с модели, тоже самое, пишет Bad Request

**Comment by fourclub** [comment]
я еще сам покавыряюсь погляжу что к чему, и если что отпишу

**Comment by chiliec** [comment]
Отлично!
Вообще, я подозреваю что проблема с настройками парсинга URL и какими-нибудь конфликтами в запросе на [экшен vote](https://github.com/Chiliec/yii2-vote/blob/master/controllers/DefaultController.php#L16). Посмотрите куда уходит javascript-запрос в браузере.

**Comment by fourclub** [comment]
ну все, порешал, поставил на другой сайт все норм, работает. А в этом реально urlManager нужно настроить, поэтому и проблема была. 
Спс за быструю реакцию )

**Comment by chiliec** [comment]
Всегда рад помочь! Спасибо что пользуетесь ;)
