### ISSUE TITLE
Не записывается дата

### ISSUE THREAD

**Issue by loveorigami** [Chiliec/yii2-vote#2]
В таблице с рейтингом в самой записи не проставляется дата
![02](https://cloud.githubusercontent.com/assets/98164/5892026/cc4a012c-a4c2-11e4-8945-90e7fc2427db.jpg)

**Comment by chiliec** [comment]
Спасибо за багрепорт! А можете в структуре таблицы показать это поле? Я задумывал что эту функцию возьмет на себя сама СУБД, у меня так:
![rating](https://cloud.githubusercontent.com/assets/982358/5892194/313db348-a4d8-11e4-9a7c-1085682a204e.png)
И ещё скажите пожалуйста версию MySQL, потому что соседнюю проблему тоже не могу воспроизвести.

**Comment by loveorigami** [comment]
У меня немного другая ).
Я накатывал Вашу миграцию, 
https://github.com/Chiliec/yii2-vote/blob/master/migrations/m150102_164631_create_rating_table.php
и у меня поля По умолчанию Дополнительно пустые.

Сделал как у Вас - заработало.
Спасибо

**Comment by loveorigami** [comment]
Для даты, наверно, лучше использовать  из коробки поведение 
use yii\behaviors\TimestampBehavior;
http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html

**Comment by chiliec** [comment]
Думал об этом... ну не знаю... чем лучше в данном случае написать

```
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date',
                'updatedAtAttribute' => 'date',
                'value' => new Expression('CURRENT_TIMESTAMP()'),
            ],
        ];
    }
```

чем одну эту строчку? При этом происходит то одно и то же, только тут мы ещё подключаем два сторонних класса. Overhead получается :)

**Comment by loveorigami** [comment]
просто в таком случае хранится дата в int как time(), не уверен,, но возможно,  чтобы поддерживалось хранение даты в разных бд (Mongo, например - http://docs.mongodb.org/manual/reference/method/Date/), а не только в Mysql как Y-m-d H:i:s
