### ISSUE TITLE
Свой вид в виджете

### ISSUE THREAD

**Issue by loveorigami** [Chiliec/yii2-vote#20]
нужно добавить публичное свойство view,
чтобы переопределить на свой вид

https://github.com/Chiliec/yii2-vote/blob/fb7db88dd5eed23b27d52fbac583c36120ce23e1/widgets/Vote.php#L115

**Comment by chiliec** [comment]
А почему бы не переопределить путь в конфиге? https://github.com/yiisoft/yii2/blob/master/docs/guide/output-theming.md

**Comment by loveorigami** [comment]
Вспомнил, в yii2-user похожее было
https://github.com/dektrium/yii2-user/blob/master/docs/overriding-views.md
Тогда надо добавить в инструкцию...
