### ISSUE TITLE
Relation model?

### ISSUE THREAD

**Issue by Pablossoo** [Chiliec/yii2-vote#31]
Hi, how should look relation model? e.g I have table post. What I need that it working?

**Comment by chiliec** [comment]
Hi @Pablossoo and thank you for your interest in this module!

You need a mysql database (not tested in other databases). Table should have a primary key (PK). And model for this table, for example Post.

In module settings you can to set like this:
```php
'models' => [
    123 => \common\models\Post::className()
],
```
where key 123 - id for link model in module auxiliary tables, value - path to class name definition (this needs for reduce table size - we stored only integer key).

If you have problems with integration module, feel free to ask any questions!

**Comment by Pablossoo** [comment]
Ok, let me explain my problem more precisely.

My entity model

`
class Adresssite extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'adresssite';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['adress'], 'string', 'max' => 255],
            [['adress'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_adress' => 'Id Adress',
            'adress' => 'Adress',
        ];
    }

  
}
`
Now if I set all config like as tutorial, but I use a basic app yii2- it's any problem? 

` 'bootstrap' => ['log',
        'chiliec\vote\components\VoteBootstrap',
    ],
     'vote' => [
            'class' => 'chiliec\vote\Module',
            // show messages in popover
            'popOverEnabled' => true,
            // global values for all models
            // 'allowGuests' => true,
            // 'allowChangeVote' => true,
            'models' => [
                // example declaration of models
                     //   app\models\Adresssite::className(),   if unncoment  gets Uncaught Error: Class 'app\models\Adresssite' not found in... 
                // 'backend\models\Post',
                // 2 => 'frontend\models\Story',
                // 3 => [
                //     'modelName' => \backend\models\Mail::className(),
                //     you can rewrite global values for specific model
                //     'allowGuests' => false,
                //     'allowChangeVote' => false,
                // ],
            ],

            ],
`
in  next step I put widget to view 

`echo \chiliec\vote\widgets\Vote::widget([
    'model' => $data,
    // optional fields
    // 'showAggregateRating' => true,
]);`

but if  I try click voteup or vote down I get error 

SyntaxError: expected expression, got ','

What is differance beetwen model agregate and agreagate_rating?

**Comment by Pablossoo** [comment]
Ok, let me explain my problem more precisely.

My entity model

   class Adresssite extends \yii\db\ActiveRecord
   {

    public static function tableName()
     {
       return 'adresssite';
     }

      public function rules()
       {
          return [
             [['adress'], 'string', 'max' => 255],
             [['adress'], 'unique'],
          ];
     }


      public function attributeLabels()
        {
           return [
               'id_adress' => 'Id Adress',
               'adress' => 'Adress',
           ];
          }
     }


Now if I set all config like as tutorial, but I use a basic app yii2- it's any problem? 


     'bootstrap' => ['log',
          'chiliec\vote\components\VoteBootstrap',
      ],
     'vote' => [
            'class' => 'chiliec\vote\Module',
            // show messages in popover
            'popOverEnabled' => true,
            // global values for all models
            // 'allowGuests' => true,
            // 'allowChangeVote' => true,
            'models' => [
                // example declaration of models
                     //   app\models\Adresssite::className(),   if unncoment  gets Uncaught Error: Class 'app\models\Adresssite' not found in... 
                // 'backend\models\Post',
                // 2 => 'frontend\models\Story',
                // 3 => [
                //     'modelName' => \backend\models\Mail::className(),
                //     you can rewrite global values for specific model
                //     'allowGuests' => false,
                //     'allowChangeVote' => false,
                // ],
            ],

            ],


in  next step I put widget to view 

     echo \chiliec\vote\widgets\Vote::widget([
        'model' => $data,
        // optional fields
        // 'showAggregateRating' => true,
     ]);

but if  I try click voteup or vote down I get error 

     SyntaxError: expected expression, got ','

What is differance beetwen model agregate and agreagate_rating?

**Comment by chiliec** [comment]
> I use a basic app yii2- it's any problem?

It's not a problem. I think your model not in `app\models\`. Before class declaration you watch line like `namespace app\models;` ?

> but if I try click voteup or vote down I get error
SyntaxError: expected expression, got ','

uncomment this line too:

<img width="573" alt="screenshot 2016-12-01 17 01 14" src="https://cloud.githubusercontent.com/assets/982358/20793232/d85e5488-b7e7-11e6-9de0-3da47b2ee63b.png">

> What is differance beetwen model agregate and agreagate_rating?

aggregate contains all votes, aggregate_rating contains only aggregate data for every id (this needs for improving performance).

**Comment by Pablossoo** [comment]
Still not working but...
I can;t use   app\models\Adresssite::className(), only class, now i doesn't get an error (class not found). My entity has namespace app\models.
But still show error  SyntaxError: expected expression, got ','


my new config

            'vote' => [
            'class' => 'chiliec\vote\Module',
            // show messages in popover
            'popOverEnabled' => true,
            // global values for all models
            // 'allowGuests' => true,
            // 'allowChangeVote' => true,
            'models' => [
                app\models\Adresssite::class,
            ],
        ],

Ok I think find error. In console at onclick function 
onclick="vote(0, , 'like');
onclick="vote(0, , 'dislike');

How it fix?

**Comment by chiliec** [comment]
`::class` not the same to `::className()`. Hmm, try to change config like this:
```php
'models' => [
    ['modelName' => 'app\models\Adresssite'],
],
```

**Comment by Pablossoo** [comment]
Ok, it's resolve this problem.  Now what is second problem with onclick?

**Comment by chiliec** [comment]
Are you sure that your model have Primary key? Because you didn't have target id (which is `primaryKey()[0]`)

**Comment by Pablossoo** [comment]
Ya, he has PK, look

https://gyazo.com/4f50997666b667bf2c4710dacdc43694

**Comment by chiliec** [comment]
```php
var_dump($this->primaryKey());
```
Can you exec this code in model and write result here?

**Comment by Pablossoo** [comment]
Ya, I created new method with this code and I called in view. 

$model->myAction();

result;

array(1) { [0]=> string(9) "id_adress" }

**Comment by chiliec** [comment]
Fine! Now try exec:
```php
var_dump($this::className());
```

**Comment by Pablossoo** [comment]
string(21) "app\models\Adresssite"

**Comment by chiliec** [comment]
Great! In module config written this string?

**Comment by Pablossoo** [comment]
'modules' => [

        'vote' => [
            'class' => 'chiliec\vote\Module',
            // show messages in popover
            'popOverEnabled' => true,
             'allowGuests' => true,
             'allowChangeVote' => true,
            'models' => [

                ['modelName' => 'app\models\Adresssite'],
            ],
        ],
....
]

className() still not  working.

**Comment by chiliec** [comment]
Very strange, it should work :(
Is your project located in somewhere in open source?

**Comment by Pablossoo** [comment]
OK.
so it's application; 
https://github.com/Pablossoo/basic
Controller  it siteController , action actionShowCommentSite($id) (she render view)
view/site/site.php

config you have in config folder.

if you want I can sent my database sql file and maybe you try reproduce my issue.

**Comment by chiliec** [comment]
Sure, put your sql file in this repository.

**Comment by chiliec** [comment]
Closed because no response for a long time.
