### ISSUE TITLE
Пропадает пробел

### ISSUE THREAD

**Issue by A1exeyDunin** [Chiliec/yii2-vote#32]
Здравствуйте. Подскажите пожалуйста, где поправить следующее? :
в файле widgets/views/vote.php я изменил вид лайков/дизлайков. 
```
<button type="button" class="btn btn-default5">
		<span id="vote-up-<?=$modelId?>-<?=$targetId?>" class="fa fa-icons fa-heart" onclick="vote(<?=$modelId?>, <?=$targetId?>, 'like'); return false;" style="cursor: pointer;">&nbsp;<?=$likes?></span>
	</button>
```
Перед количеством есть `&nbsp;`. Когда заходишь на страницу, все хорошо http://joxi.ru/brRjnNQtqwj1r1. Но когда проголосуешь, то пробел пропадает http://joxi.ru/a2XDY0KijxXk2g.

**Comment by chiliec** [comment]
Это происходит потому, что скрипт обновляет весь текст внутри этого нужного id https://github.com/Chiliec/yii2-vote/blob/master/widgets/Vote.php#L97
Можете добавить неразрывный пробел перед тегом (предпочтительно) или изменить скрипт.

**Comment by A1exeyDunin** [comment]
Спасибо.
