### ISSUE TITLE
Вид после обновления до v1.4

### ISSUE THREAD

**Issue by loveorigami** [Chiliec/yii2-vote#6]
Обновил модуль.
Голосование не работает. 
Сейчас запрос идет на www.site.ru/vote
https://github.com/Chiliec/yii2-vote/blob/master/Display.php#L98
так работает
 $this->vote_url = Yii::$app->getUrlManager()->createUrl(['vote/default/vote']);

**Comment by chiliec** [comment]
Спасибо!
