### ISSUE TITLE
Error in backend

### ISSUE THREAD

**Issue by loveorigami** [Chiliec/yii2-vote#7]
Зашел в админку.
Выдало ошибку. В логе винит поведение vote.
Отключил его - ошибки нет.
![2015-01-29_21-33-04](https://cloud.githubusercontent.com/assets/98164/5963587/a7d6a950-a7fe-11e4-8a79-d81371a98b57.jpg)

**Comment by chiliec** [comment]
Как бы это воспроизвести...

**Comment by loveorigami** [comment]
Стандартная модель из gii
Добавляем 

``` php
class Article extends \yii\db\ActiveRecord
{
    const STATUS_PUBLISHED = 1;
    const STATUS_DRAFT = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%article}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => \chiliec\vote\behaviors\RatingBehavior::className(),
                'model_name' => 'Article', // name of this model
            ],
        ];
    }
```

перехожу на сгенерированный через Crud контроллер в админке. Получаю ошибку выше

**Comment by chiliec** [comment]
А админка которая? И можете конфиг модуля показать?

**Comment by chiliec** [comment]
Подозреваю что ошибка в большой букве в названии модели `Article`. В конфиге [вот здесь](https://github.com/Chiliec/yii2-vote/issues/3#issuecomment-71648678) с маленькой написано, а здесь почему-то с большой.

**Comment by loveorigami** [comment]
конфиг модуля

``` php
        'vote' => [
            'class' => 'chiliec\vote\Module',
            'matchingModels' => [ // matching model names with whatever integer ID
                'Article' => 1,
            ],
            'allow_guests' => false, // if true remember IP for guests, otherwise - UserID
            'allow_change_vote' => false,
        ],
```
- Модель из Gii
- Crud из Gii

![crud](https://cloud.githubusercontent.com/assets/98164/5964605/86fc9c6e-a806-11e4-9a36-0d86cb9b6f6c.jpg)
- Захожу на actionIndex - работает.
  ![2015-01-29_22-36-32](https://cloud.githubusercontent.com/assets/98164/5964724/63939894-a807-11e4-8da8-122376f0729f.jpg)
- Добавляю поведение Vote - выдает ошибку

**Comment by loveorigami** [comment]
Это не в виджете ошибка. в gridView.

Было с маленькой. Я подумал, что class с большой - и переделал все с большой. Голосование происходит. А вот в gridView - ошибка.

**Comment by chiliec** [comment]
По ошибке явно видно, что из поведения он пытается получить название модели с маленькой буквы. Проверьте ещё разок :)
![error](https://cloud.githubusercontent.com/assets/982358/5965085/2267c110-a81b-11e4-8253-374170854dd9.png)

**Comment by loveorigami** [comment]
Да нет ).
Я ж писал, что по всякому пробовал. То ошибка, когда было с маленькой.
Затем - поменял с большой - ошибка осталась. Сейчас так

``` php
#0 X:\domains\ori.yii\vendor\chiliec\yii2-vote\behaviors\RatingBehavior.php(41): chiliec\vote\models\Rating->getRating('Article', 9)
```

**Comment by loveorigami** [comment]
перед этим
https://github.com/Chiliec/yii2-vote/blob/master/models/Rating.php#L114
сделал
var_dump($model_id);

получил boolean false

И видно - где выводится исключение...

**Comment by loveorigami** [comment]
а здесь
https://github.com/Chiliec/yii2-vote/blob/master/models/Rating.php#L98
var_dump($matchingModels); 

выводит null

**Comment by loveorigami** [comment]
все... решил ))
конфиг был во frontend-e
перенес в common. Заработало....

**Comment by chiliec** [comment]
:+1:
