### ISSUE TITLE
Ошибка в логике голосования...

### ISSUE THREAD

**Issue by loveorigami** [Chiliec/yii2-vote#8]
Если нажимать vote_up, затем vote_down и так несколько раз - каждый раз выходит сообщение об успешном голосовании...

![01](https://cloud.githubusercontent.com/assets/98164/5964077/5067e0cc-a802-11e4-8cbc-ee7163c58690.jpg)
![02](https://cloud.githubusercontent.com/assets/98164/5964078/50689468-a802-11e4-83c0-6c489a671573.jpg)

**Comment by chiliec** [comment]
Так это не баг, а фича :)
`'allow_change_vote' => false,`
в конфиге модуля отключит возможность менять голос

**Comment by loveorigami** [comment]
a )))... а я на настойки и не смотрю ) у меня с v1.3 они.
